version: "3"

services:

  siabim_django:
    image: siabim_django:2.2.5
    volumes:
      - ../django/siabim/:/siabim/siabim/
    working_dir: /siabim/siabim/
    command: gunicorn siabim.wsgi:application 0.0.0.0:8000

  siabim_gulp:
    image: siabim_gulp:node_10.16.3 
    volumes:
      - ../gulp/siabim/:/siabim/
    command: gulp watch
