version: "3"

services:

  siabim_django:
    image: siabim_django:2.2.5
    volumes:
      - ../django/siabim/:/siabim/siabim/
    working_dir: /siabim/siabim/
    command: gunicorn siabim.wsgi:application -b 0.0.0.0:8000

  siabim_gulp:
    image: siabim_gulp:node_10.16.3 
    volumes:
      - ../gulp/siabim/:/siabim/
      - ../staticfiles/:/staticfiles/ 
    command: gulp watch

  siabim_nginx:
    image: nginx:1.17-alpine
    ports:
      - 80:80
    volumes:
      - ../nginx/conf.d/:/etc/nginx/conf.d/

  siabim_postgresql:
    image: postgres:11.5-alpine
