version: "3"

services:

  siabim_django:
    image: siabim_django:2.2.16
    depends_on:
      - siabim_postgresql
    env_file:
      - ./.env_siabim_django
    volumes:
      - ../django/siabim/:/siabim/
      - ../staticfiles/django/:/staticfiles/
    working_dir: /siabim/
    command: gunicorn siabim.wsgi:application -b 0.0.0.0:8000

  siabim_gulp:
    image: siabim_gulp:node_10.16.3 
    volumes:
      - ../gulp/siabim/:/siabim/
      - ../staticfiles/:/staticfiles/ 
    command: gulp watch
    ports:
      - 35729:35729

  siabim_nginx:
    depends_on:
      - siabim_django
    image: siabim_nginx:1.17
    ports:
      - 80:80
    volumes:
      - ../nginx/conf.d/:/etc/nginx/conf.d/
      - ../staticfiles/django/:/staticfiles/
      - ../staticfiles/css/production/:/static/css/production/
      - ../staticfiles/js/production/:/static/js/production/
      - ../staticfiles/img/:/static/img/
      - ../staticfiles/fonts/:/static/fonts/

  siabim_postgresql:
    image: postgres:11.5-alpine
    env_file:
      - ./.env_siabim_postgresql
