version: "3"

services:
    django:
      image: siabim_django:2.2.5
      volumes:
        - ../django/siabim/:/siabim/siabim/
      working_dir: /siabim/siabim/
      command: gunicorn siabim.wsgi:application 0.0.0.0:8000
