# Generated by Django 2.2.11 on 2020-03-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagemodel',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
